### ISSUE TITLE
hello, Can you add DC-dimming support?

### ISSUE THREAD

**Issue by z826540272** [pascua28/s5-kernel#3]
many galaxy S5 screen will be flicker at low temperature, and PWM flickering will hurt my eyes .
but
someone has solved this problem by apply hard dc dimming feature in kernel.
here is the source code for galaxy s10+. 
I hope you guys can port this to galaxy S5

https://github.com/DevriesL/Beyond2QLTE_ImageBreaker/commit/39322086134bbcd00255a473437b19b3c2c3118f

![IMG_20191101_165604_1](https://user-images.githubusercontent.com/56025847/68184405-e535b880-ffd9-11e9-9363-4817a857b9e4.jpg)

**Comment by z826540272** [comment]
the source code 15%~100% brightness is hardware DC dimming, 15% or less uses SDE for DC dimming.

**Comment by pascua28** [comment]
Hello, I implemented smart dimming using color value adjustments. Sorry I didn't pay attention on your second comment so I erroneously set the brightness threshold to 35%. Future updates may include increasing saturation value a little bit to compensate for the color quality loss. Actual implementation: c777bdbb9ae42efc19586acc5ffef517379991d4

I got the pcc interpolation equation based on two point-slope method. This is so it will accurately scale the pcc value to reproduce virtually the same amount of dimming. The 6600 value is what I chose as the pcc rgb minimum cause it looks like it has the same lowest brightness I can see compared to the previous dimming method. Also added the pcc ratio computation so that changes to the rgb values (like LineageOS LiveDisplay) will be scaled accordingly, producing the same visual picture.

Can you check if the unwanted flicker also occurs at 15% on our device?

**Comment by pascua28** [comment]
072c2e443e1de2ea886b693e83a2b725c8a84b3f
